### ISSUE TITLE
What was the motivation behind this 'next big thing' ? :)

### ISSUE THREAD

**Issue by acpmasquerade** [aryalprakash/fb-dots-blocker#2]
#question ??

**Comment by aryalprakash** [comment]
haha dai..
Because Mark Zuckerberg didn't address my [open letter](https://www.facebook.com/aryalprakash/posts/10211066625252552) to him and have to do this for my own good :stuck_out_tongue:

**Comment by aryalprakash** [comment]
But some more useful ideas based on this are coming. :smile:

**Comment by acpmasquerade** [comment]
When I first read your post about "dot-comments", i didn't take the word literally. Instead, I thought it had more semantic meaning, where less sensbile comments were regarded as dots.

I checked the code, and it was literally checking the DOTS.

Did I miss any such trend where people were frequently commenting with single dot or comma ? This was my actual question :)

**Comment by aryalprakash** [comment]
![image](https://cloud.githubusercontent.com/assets/3658290/20921399/fe60ff4a-bbcb-11e6-83c2-ab1b5a98494a.png)
![image](https://cloud.githubusercontent.com/assets/3658290/20921526/a985be2e-bbcc-11e6-841a-f44115063a15.png)
![image](https://cloud.githubusercontent.com/assets/3658290/20921535/b7fc55d0-bbcc-11e6-8e82-00e786004c65.png)

I get to see these frequently in my news feed. :smiley:

**Comment by acpmasquerade** [comment]
thoplo

**Comment by acpmasquerade** [comment]
A suggestion, Include the original thoplo is some way.

**Comment by aryalprakash** [comment]
thoplo pani included chha :)
